name: CI

on:
    push:
        branches:
        - master
    pull_request:
        branches:
            - master

jobs:
    release:
        runs-on: windows-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.3'
            - run: go version

            - name: Install Dependecies
              run: |
                go get .\src
                go get .\src\components
                go get .\src\handlers

            - name: Build
              run: go build -v ./...

            - name: Check File Paths
              run: |
                cd .\src
                ls

            - name: Create Release
              uses: actions/upload-artifact@v4
              with:
                name: VTApp
                path: ./VTApp.exe
                if-no-files-found: error

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "latest"
                prerelease: true
                title: "Unstable/Development Build"
                files: |
                    dist/VTApp.exe
