name: CI

on:
    push:
        branches:
        - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.3'
            - run: go version

            - name: Install Dependecies
              run: |
                go get .\src
                go get .\src\components
                go get .\src\handlers

            - name: Build
              run: go build -o VTApp.exe -v .\src

            - name: Check File Paths
              run: |
                ls
                cd .\src
                ls

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: VTApp
                path: D:\a\VTApp\VTApp\VTApp.exe
                if-no-files-found: error

    pre-release:
        needs: build
        name: "Pre Release"
        runs-on: "ubuntu-latest"

        steps:
            - uses: actions/checkout@v2

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: VTApp
                path: VTApp.zip/VTApp.exe

            - name: "Build & test"
              run: |
                echo "done!"

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "latest"
                prerelease: true
                title: "Development Build"
                files: |
                  VTApp.zip/VTApp.exe
